### ISSUE TITLE
[Feature Request]: Gentoo Ebuild

### ISSUE THREAD

**Issue by thamognya** [deepjyoti30/yaf#2]
I would like to ask for permission to develop and later on add an ebuild for Gentoo users to install this fetching app. This would allow Gentoo users to install this fetching package from their portage package manager instead of building it from source by themselves.

**Comment by deepjyoti30** [comment]
@ThamognyaKodi Sure, go ahead.

Don't forget to update the README with instructions to install on Gentoo.

**Comment by thamognya** [comment]
Thank you for the confirmation @deepjyoti30 .
