### ISSUE TITLE
enhancement: choosing the install directory

### ISSUE THREAD

**Issue by clyhtsuriva** [deepjyoti30/yaf#3]
As of today, it's not possible to change the install directory except from manually modifying the Makefile.

I propose to add the `DESTDIR` variable set with `/usr/bin` by default.
Therefore, to change it, a user will simply have to set the variable while calling make if he desires to.

**Example :**
```
make install DESTDIR="/home/user/.local/bin"
```

**Comment by deepjyoti30** [comment]
#4 is merged. Thanks for the PR!
