### ISSUE TITLE
yaf on Gentoo, formatting problem with /etc/os-release

### ISSUE THREAD

**Issue by deprecated-dot** [deepjyoti30/yaf#5]
`❯ ./build/yaf

pac@descartes
━━━━━━━━━━━━━

▪ memory  19% of 49419m
▪ disk    31 GB / 67 GB
▪ os      Gentoo LinuxANSI_COLOR=1;32HOME_URL=https://www.gentoo.org/SUPPORT_URL=https://www.gentoo.org/support/BUG_REPORT_URL=https://bugs.gentoo.org/VERSION_
▪ kernel  5.15.16-gentoo-x86_64
▪ shell   zsh
▪ uptime  24h 30m`

Screenshot [here](https://i.postimg.cc/VkkD0V4Z/ps-20220122213403.png) for further clarity.

**Comment by deepjyoti30** [comment]
@deprecated-dot Could you provide the `/etc/os-release` file content from your system? On my Arch system, parsing the OS from `/etc/os-release` is working fine.

**Comment by deepjyoti30** [comment]
@deprecated-dot Thanks for raising the issue. Could you try 6865d68 on your system locally and let me know if it works?

You can follow the following steps:

1. `sudo make install`
2. `yaf`

`yaf` should print proper OS name now, I tested it locally and it works for me.

**Comment by deprecated-dot** [comment]
`❯ ./build/yaf

pac@descartes
━━━━━━━━━━━━━

▪ uptime  46h 54m
▪ memory  12% of 49419m
▪ disk    32 GB / 67 GB
▪ os      Gentoo Linux
▪ kernel  5.16.2-gentoo-x86_64
▪ shell   zsh

 ~/yaf  master     `
 
 
 Perfect. It now functions flawlessly. Great work!
 
 Edit: closing this issue unless you raise any objections.
